name: spacex_clean_scope
description: A Flutter project with the SpaceXAPI.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # * state management
  flutter_riverpod: ^0.12.4
  freezed_annotation: ^0.12.0

  # * networking
  dio: ^3.0.10

  # * internationalization
  i18n_extension: ^2.0.0

  # * features
  dragons:
    path: packages/dragons

  # * scoped packages
  network_manager:
    git:
      url: git://github.com/NoScopeDevs/network_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  # * code generation
  build_runner: any
  flutter_gen_runner: any
  freezed: any

  # * linter
  very_good_analysis: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/img/

flutter_gen:
  output: lib/gen/
