name: spacex_clean_scope
description: A Flutter project with the SpaceXAPI.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # * State Management
  flutter_riverpod: ^0.12.4
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # * Code Generation
  build_runner: any
  freezed: any

  # * Linter
  very_good_analysis: ^1.0.4

flutter:
  uses-material-design: true
